version: "3"

services:

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test 
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:latest 

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "8080:1337"  
    environment:
      REDIS_HOST: redis 
      REDIS_PORT: 6379 
      MYSQL_HOST: mysql  
      MYSQL_USER: root  
      MYSQL_PASSWORD: root
      MYSQL_DB: test
      FILE_PATH_TO_CHECK: "${FILE_PATH_TO_CHECK:-./dummy.txt}" 
    depends_on:
      - mysql
      - redis
    volumes:
      - .:/app
    hostname: mydocker

volumes:
  mysql-data: {}
